title: A1 Language Certification Paper
description: Practice papers for A1 language certification
baseurl: ""
url: ""

# Navigation
navigation:
  - title: الامتحان
    url: /
  - title: أسئلة عشوائية
    url: /about.html
  - title: كلمات مهمة
    url: /keywords.html
  - title: تذكيرات أساسية للامتحان
    url: /reminders.html
  - title: ربط الجمل
    url: /crossword.html

# Jekyll settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Include JSON files and directories
include:
  - index.json
  - past_papers
  - past_papers_images
  - simple_question_bank
  - keywords_in_arabic
  - key_reminders
  - crossword
