title: A1 Language Certification Paper
description: Practice papers for A1 language certification
baseurl: ""
url: ""

# Navigation
navigation:
  - title: تمارين الجمل
    url: /drills.html
  - title: املأ الفراغات
    url: /fill_blanks.html
  - title: تمارين الامتحان
    url: /exam_drills.html

# Jekyll settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Include JSON files and directories
include:
  - index.json
  - past_papers
  - past_papers_images
  - simple_question_bank
  - keywords_in_arabic
  - key_reminders
  - crossword
  - drills
  - new_exams
  - fill_blanks
  - exam_drills
